apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyrics-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ronsha001/devtube-chart.git
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: lyrics

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true