apiVersion: v1
kind: Service
metadata:
  name: {{ include "lyrics.fullname" . }}-app
spec:
  selector:
    app: lyrics
  {{- if or (.Values.lyrics.nginx.enabled) (.Values.lyrics.ingress.enabled) }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end}}
  ports:
    - protocol: TCP
      port: {{ .Values.lyrics.port }}
      targetPort: {{ .Values.lyrics.port }}