{{- if .Values.lyrics.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lyrics.fullname" . }}-nginx
  namespace: {{ .Values.lyrics.namespace }}
  labels:
    app: {{ include "lyrics.fullname" . }}-nginx
spec:
  replicas: {{ .Values.lyrics.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ include "lyrics.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "lyrics.fullname" . }}-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
        - name: static-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        hostPath: /home/ron/Desktop/Lyrics/Lyrics-App/nginx/nginx.conf
        type: FileOrCreate
      - name: static-files
        hostPath: /home/ron/Desktop/Lyrics/Lyrics-App/static
        type: DirectoryOrCreate
{{- end }}
