apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lyrics.fullname" . }}-nginx
  namespace: {{ .Values.lyrics.namespace }}
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  temaplate:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        