apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lyrics.fullname" . }}-nginx
  namespace: {{ .Values.lyrics.namespace }}
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  temaplate:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
        - name: static-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        hostPath: /home/ron/Desktop/Lyrics/Lyrics-App/nginx/nginx.conf
      - name: static-files
        hostPath: /home/ron/Desktop/Lyrics/Lyrics-App/static