{{- if .Values.lyrics.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static
  namespace: {{ .Values.lyrics.namespace }}
data:
  index.js: {{ .Values.ingress.static_files.index_js }}
  main.css: {{ .Values.ingress.static_files.main_css }}
  index.html: {{ .Values.ingress.static_files.index_html }}
{{- end }}
