lyrics:
  namespace: lyrics
  replicas: 2
  port: 8000
  image:
    name: 651569844/lyrics
    tag: 1.0.1
    pullPolicy: Always
  resources:
    requests:
      memory: 250Mi
      cpu: 250m
    limits:
      memory: 500Mi
      cpu: 500m
  nginx:
    enabled: true
    port: 80
    replicas: 2

ingress:
  enabled: true
  host: lyrics

ingress-nginx:
  controller:
    service:
      nodePorts:
        http: 30003
        https: 30004

redis:
  master:
    persistence:
      size: 1Gi
  replica:
    persistence:
      size: 1Gi