lyrics:
  namespace: lyrics
  replicas: 2
  port: 8000
  image:
    name: 651569844/lyrics
    tag: 1.0.1
  resources:
    requests:
      memory: 250Mi
      cpu: 250m
    limits:
      memory: 500Mi
      cpu: 500m
  ingress:
    enabled: false
  nginx:
    enabled: true
    port: 80
    replicas: 2