apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  namespace: lyrics
  labels:
    app: app-test
  annotations:
    argocd-image-updater.argoproj.io/image-list: 651569844/lyrics:~1
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - image: 651569844/lyrics:1.1.1
        name: lyrics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_DNS
          value: lyrics-app-redis-master
        - name: REDIS_PASSWORD
          value: "123"
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            memory: 500Mi
            cpu: 500m